const puzzles = [
  { emojis: "💪 🐘 👑", answer: "Baahubali", options: ["Baahubali", "Magadheera", "RRR", "Pushpa"], hint: "A warrior prince fights for his throne" },
  { emojis: "🔥 💧 🏴", answer: "RRR", options: ["RRR", "Pokiri", "Temper", "Jersey"], hint: "Two rebels fight against British oppression" },
  { emojis: "🌺 🪵 🏔️", answer: "Pushpa", options: ["Pushpa", "Rangasthalam", "Srimanthudu", "Eega"], hint: "A smuggler rises in the red sanders trade" },
  { emojis: "🏥 ❤️ 🍺", answer: "Arjun Reddy", options: ["Arjun Reddy", "Maharshi", "Taxiwaala", "Fidaa"], hint: "A surgeon's downfall through love and loss" },
  { emojis: "👨‍👦 🏠 💃", answer: "Ala Vaikunthapurramuloo", options: ["Ala Vaikunthapurramuloo", "Sarileru Neekevvaru", "Bheemla Nayak", "Nannaku Prematho"], hint: "Two babies swapped at birth" },
  { emojis: "🪰 💀 ❤️", answer: "Eega", options: ["Eega", "Makkhi", "Awe", "Ohm Shanthi Oshaana"], hint: "A fly seeks revenge for love" },
  { emojis: "⚔️ 🐴 ♻️", answer: "Magadheera", options: ["Magadheera", "Baahubali", "Chatrapathi", "Bimbisara"], hint: "Reincarnation and past life love story" },
  { emojis: "💰 🏘️ ❤️", answer: "Srimanthudu", options: ["Srimanthudu", "Businessman", "Julayi", "Dookudu"], hint: "A billionaire builds homes for the poor" },
  { emojis: "🌾 👂 🏘️", answer: "Rangasthalam", options: ["Rangasthalam", "Fidaa", "Mahanati", "Pelli Choopulu"], hint: "A deaf man saves his village from crime" },
  { emojis: "🏠 👴 💃", answer: "Attarintiki Daredi", options: ["Attarintiki Daredi", "Khaidi No 150", "Agnyaathavaasi", "Sardaar Gabbar Singh"], hint: "A girl dances to win her grandfather's love" },
  { emojis: "🤠 🔫 😎", answer: "Gabbar Singh", options: ["Gabbar Singh", "Pokiri", "Khaleja", "Mirchi"], hint: "A rogue cop with a mysterious past" },
  { emojis: "🔫 🕺 🎭", answer: "Pokiri", options: ["Pokiri", "Temper", "Jalsa", "Gabbar Singh"], hint: "A young man infiltrates a gang as a killer" },
  { emojis: "👮 😡 ⚖️", answer: "Temper", options: ["Temper", "Pokiri", "Mirchi", "Dookudu"], hint: "A corrupt cop reforms after a tragedy" },
  { emojis: "🔒 💯 🕺", answer: "Khaidi No 150", options: ["Khaidi No 150", "Attarintiki Daredi", "Sardaar Gabbar Singh", "Agnyaathavaasi"], hint: "A convict's lookalike saves a village" },
  { emojis: "🏆 🎾 💪", answer: "Jersey", options: ["Jersey", "Maharshi", "Taxiwaala", "Chi La Sow"], hint: "An aging cricketer makes his comeback" },
  { emojis: "🌹 💌 🚂", answer: "Fidaa", options: ["Fidaa", "Pelli Choopulu", "Mahanati", "Geetha Govindam"], hint: "A Telangana village girl falls for a Telugu-American" },
  { emojis: "🎬 🎥 👑", answer: "Mahanati", options: ["Mahanati", "Fidaa", "Rangasthalam", "Awe"], hint: "Biopic of legendary actress Savitri" },
  { emojis: "🍳 👩 💕", answer: "Pelli Choopulu", options: ["Pelli Choopulu", "Fidaa", "Geetha Govindam", "Chi La Sow"], hint: "Two opposites meet during a cooking venture" },
  { emojis: "🌙 💛 🛺", answer: "Geetha Govindam", options: ["Geetha Govindam", "Fidaa", "Taxiwaala", "Majili"], hint: "A lecturer falls for a feisty village girl" },
  { emojis: "💔 🥃 ⚽", answer: "Majili", options: ["Majili", "Jersey", "Arjun Reddy", "Maharshi"], hint: "A failed cricketer drowns in grief and alcohol" },
  { emojis: "🚗 👻 😱", answer: "Taxiwaala", options: ["Taxiwaala", "Awe", "Eega", "Geethanjali"], hint: "A cab driver buys a haunted taxi" },
  { emojis: "🎓 💼 🌟", answer: "Maharshi", options: ["Maharshi", "Srimanthudu", "Jersey", "Julayi"], hint: "A billionaire returns to help his struggling village" },
  { emojis: "🧠 👁️ 🌀", answer: "Awe", options: ["Awe", "Taxiwaala", "Geethanjali", "Kshanam"], hint: "Six strangers connect in a mysterious restaurant" },
  { emojis: "🔍 💑 📱", answer: "Kshanam", options: ["Kshanam", "Awe", "Agent Sai Srinivasa", "Evaru"], hint: "A man searches for his missing ex-girlfriend" },
  { emojis: "⚔️ 👑 🕰️", answer: "Bimbisara", options: ["Bimbisara", "Magadheera", "Baahubali", "Chatrapathi"], hint: "A cruel ancient king time-travels to the present" },
  { emojis: "🧪 🔬 💀", answer: "HIT", options: ["HIT", "Evaru", "Kshanam", "Agent Sai Srinivasa"], hint: "A detective investigates a missing person case" },
  { emojis: "❓ 🕵️ 😰", answer: "Evaru", options: ["Evaru", "HIT", "Kshanam", "Awe"], hint: "A psychological thriller — who is lying?" },
  { emojis: "🦁 🌿 🏹", answer: "Chatrapathi", options: ["Chatrapathi", "Vikramarkudu", "Magadheera", "Mirchi"], hint: "A fearless young man fights for refugees" },
  { emojis: "👮 🌶️ 💥", answer: "Vikramarkudu", options: ["Vikramarkudu", "Chatrapathi", "Dookudu", "Mirchi"], hint: "A fierce cop takes on a village tyrant" },
  { emojis: "💣 😂 🕵️", answer: "Dookudu", options: ["Dookudu", "Julayi", "Mirchi", "Son of Satyamurthy"], hint: "A crazy ACP goes undercover with a fake family" },
  { emojis: "🧩 🤣 💰", answer: "Julayi", options: ["Julayi", "Dookudu", "Businessman", "Son of Satyamurthy"], hint: "A lazy guy stumbles into a heist" },
  { emojis: "🌊 💸 🧨", answer: "Businessman", options: ["Businessman", "Julayi", "Okkadu", "Athadu"], hint: "A ruthless don builds an underworld empire" },
  { emojis: "🥊 🏆 ❤️", answer: "Okkadu", options: ["Okkadu", "Athadu", "Pokiri", "Mirchi"], hint: "A Kabaddi player fights a powerful villain for love" },
  { emojis: "🔫 🎭 🏃", answer: "Athadu", options: ["Athadu", "Okkadu", "Pokiri", "Businessman"], hint: "A hitman assumes a dead man's identity" },
  { emojis: "💐 🌸 😊", answer: "Bommarillu", options: ["Bommarillu", "Happy", "Sainikudu", "Nuvvostanante Nenoddantana"], hint: "A son rebels against his overprotective father for love" },
  { emojis: "💒 👫 🏡", answer: "Nuvvostanante Nenoddantana", options: ["Nuvvostanante Nenoddantana", "Bommarillu", "Happy", "Dil"], hint: "Families feud but young love wins" },
  { emojis: "🕊️ 🌅 🎶", answer: "Ye Maaya Chesave", options: ["Ye Maaya Chesave", "Nuvvostanante Nenoddantana", "Bommana Bros", "Brindavanam"], hint: "A Hindu-Christian love story" },
  { emojis: "🌴 🏖️ 💞", answer: "Brindavanam", options: ["Brindavanam", "Ye Maaya Chesave", "Teen Maar", "Julayi"], hint: "A loyal friend helps a girl escape a forced marriage" },
  { emojis: "👨‍👩‍👦 💔 🎵", answer: "Son of Satyamurthy", options: ["Son of Satyamurthy", "Julayi", "Businessman", "Dookudu"], hint: "A son takes responsibility after his father's death" },
  { emojis: "🌺 🩸 ⚡", answer: "Mirchi", options: ["Mirchi", "Chatrapathi", "Vikramarkudu", "Gabbar Singh"], hint: "A carefree man fights a deadly enemy for his village" }
];

module.exports = puzzles;
